# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  host: ec2-50-17-212-238.compute-1.amazonaws.com

  pool: 5
  username: wlgtzjjmpmzcvt
  password: bh3CUBgDSHhkwX7MgfPBOGwUIL

development:
  <<: *default
  host: localhost
  username: josh
  password: password
  database: socialbasin

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: ddsncj2e4lrk1c