# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e9be9237bbd41716cf54a347c0df2cc1c2c10a93c501b2cb1b32c252b4cb56cb7abae88fba713888f6ebdb57232958514165ceae65cb37603493a5f49a9b34e

test:
  secret_key_base: e3b58120d0e30294cb23961619026374a43313ce831d0f49a0b00fa09dad41a470a856c86a0e17efd38170b4c8e64c61abed2de9c46b97d2831b756e6618b441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
